webapp/__init__.py
from flask import Flask
from flask.ext.sqlalchemy import SQLAlchemy
from flask.ext.uuid import FlaskUUID

from flask.ext.user import UserManager, UserMixin, SQLAlchemyAdapter
from flask.ext.user import current_user, login_required, roles_required, UserMixin

from flask import g

from .api import api
from .data import data
from .modeller import modeller
from .site import site
from .admin import admin
from .status import status
from .install import install

app = Flask(__name__)

#g.test = "lala"

FlaskUUID(app)

#Load the base configuration from settings.py
app.config.from_object('webapp.settings')

#Overwrite any settings with local_settings.py
try: app.config.from_object('webapp.local_settings')
except: print " * Local settings file coult not be imported."

from models import *

db.init_app(app)

@app.context_processor
def system_status():
    """
    This context processor makes the "system_status" variable available in all
    the templates.
    """
    status = {
        'beanstalk_workers': beanstalk.workers
    }
    return dict(system_status=status)

db_adapter = SQLAlchemyAdapter(db,  User)
user_manager = UserManager(db_adapter, app)

app.register_blueprint(modeller,    url_prefix='/modeller')
app.register_blueprint(data,        url_prefix='/data')
app.register_blueprint(api,         url_prefix='/api/v1')
app.register_blueprint(admin,       url_prefix='/admin')
app.register_blueprint(status,      url_prefix='/status')
app.register_blueprint(install,     url_prefix='/install')
app.register_blueprint(site)

if __name__ == "__main__":
	app.run()

webapp/admin/__init__.py
from flask import Blueprint

admin=Blueprint('admin',__name__,template_folder='templates',static_folder='static')

#@admin.before_request
#def restrict_to_admin_roles():
#    if not user.is_admin:
#        return redirect(...)

import views

webapp/admin/views.py
import os
import re
import subprocess
import uuid
import json
import glob 
import StringIO
import tempfile

from osgeo import ogr,osr
from owslib.wcs import WebCoverageService

from . import admin

from flask import g, current_app, render_template, request, jsonify, make_response, flash, url_for, redirect
from flask.ext.user import login_required, roles_required
from datetime import datetime, timedelta

from ..models import *

@admin.route('/')
@roles_required('admin')
def home():
    return 'Hello, admin blueprint!'

@admin.route('/datasets')
@roles_required('admin')
def datasets():
    """
    Shows information on datasets
    """
    wcss=[]
    for descr,url in current_app.config.get('WCS',{}).items():
        layers=[]
        wcs = WebCoverageService(url, version='1.0.0')
        for lyr in list(wcs.contents):
            layers.append({'name':lyr,'data':wcs.contents[lyr]})
            print dir(wcs.contents[lyr])
        wcss.append({'url':url,'layers':layers})
    return render_template("admin/datasets.html",wcs=wcss)
    
@admin.route('/users', methods=["GET"])
@roles_required('admin')
def users():
    """
    Show user list with options to add admins.
    """
    users=User.query.order_by(User.id).all()
    return render_template("admin/users.html",users=users)

@admin.route('/users/<int:uid>/<string:role>/toggle', methods=["GET"])
@roles_required('admin')
def users_make_admin(uid,role):
    """
    Show user list with options to add admins.
    """
    user = User.query.get(uid)
    if user.username != 'admin':
        user.toggle_role(role)
    return redirect(url_for('admin.users'))
    
@admin.route('/users/<int:uid>/reset-api-token')
@roles_required('admin')
def users_reset_api_token(uid):
    user = User.query.get(uid)
    user.reset_api_token()
    return redirect(url_for('admin.users'))

@admin.route('/users/<int:uid>/reset-password')
@roles_required('admin')
def users_reset_password(uid):
    user = User.query.get(uid)
    new_password = user.reset_password()
    flash("New password for user <code>%s</code> is <code>%s</code>. Please write it down, this is the only time that it is shown."%(user.username,new_password),"ok")
    return redirect(url_for('admin.users'))

@admin.route('/discretization',methods=["GET","POST"])
@roles_required('admin')
def discretization():
    """
    Shows information on domain discretization
    """
    if request.method=="POST":
        #try:
        if True:
            f = request.files['shapefile']
            temp = tempfile.NamedTemporaryFile(prefix='de-', suffix='.zip')
            f.save(temp.name)
            ds = ogr.Open("/vsizip/"+temp.name)
            if ds is not None:
                d = Discretization(request.form.get('name',''), ds, int(request.form.get('cellsize',100)))
                db.session.add(d) 
                db.session.commit()
                flash("New discretization was created!","ok")
            else:
                raise Exception("Temporary file '%s' could not be opened."%(temp.name))
        #except Exception as e:
        #    db.session.rollback()
        #    flash("An exception occurred while trying to add the discretization! Hint: %s"%(e),"error")
        #finally:
            ds = None
            temp.close()
        return redirect(url_for('admin.discretization'))
    else:
        return render_template("admin/discretization.html",discretizations=Discretization.query.all())

@admin.route('/processing')
@roles_required('admin')
def processing():
    """
    Shows information on processing
    """
    jobs=Job.query.order_by(Job.date_created.desc()).limit(10)
    return render_template("admin/processing.html",jobs=jobs)
    

@admin.route('/notifications')
@roles_required('admin')
def notifications():
    """
    Show notifications sent via postgresql NOTIFY
    """
    return render_template("admin/notifications.html")

@admin.route('/workers')
@roles_required('admin')
def workers():
    """
    Shows information on connected workers
    """
    workers = Worker.query.order_by(Worker.updated.desc()).limit(10)
    return render_template("admin/workers.html", workers=workers)

@admin.route('/models/<model_name>/editor',methods=["GET","POST"])
def model_editor(model_name):
    """
    show the code editor
    """
    model=Model.query.filter_by(name=model_name).first_or_404()
    return render_template('admin/modeleditor.html',model=model)
    
@admin.route('/models/<model_name>/toggle-pin',methods=["GET"])
@roles_required('admin')
def model_toggle_pin(model_name):
    model = Model.query.filter_by(name=model_name).first_or_404()
    model.toggle_pin()
    return redirect(url_for('site.home'))
    
@admin.route('/models/<model_name>/toggle-disable',methods=["GET"])
@roles_required('admin')
def model_toggle_disable(model_name):
    model = Model.query.filter_by(name=model_name).first_or_404()
    model.toggle_disable()
    return redirect(url_for('site.home'))

@admin.route('/models/<model_name>/parameters',methods=["GET","POST"])
def model_parameters(model_name):
    """
    show the code editor
    """
    model=Model.query.filter_by(name=model_name).first_or_404()
    return render_template('admin/modelparameters.html',model=model)    

@admin.route('/models',methods=["GET","POST"])
@roles_required('admin')
def models():
    """
    Shows information on models
    """
    if request.method=="POST":
#        name=re.sub(r'\W+',' ',request.form.get("modelname","")).lower()
#        name="_".join(map(str,name.split()))
#        
#        if name == "":
#            flash("Invalid model name.")
#            return redirect(url_for('site.home'))
#        
#        model = Model.query.filter_by(name=name).first()
#        if model is not None:
#            flash("It seems like that model exists already! Please try another name.","error")
#            return redirect(url_for('site.home'))
        
        try:
            model = Model(name=request.form.get("modelname",""))
            db.session.add(model)
            db.session.commit()
        except Exception as e:
            db.session.rollback()
            flash("Something unexpected went wrong trying to add the model. Hint: %s"%(e),"error")
            return redirect(url_for('site.home'))
        else:
            return redirect(url_for('admin.model_editor',model_name=model.name))
    else:
        flash("The models admin page is no longer in use because all the models are now listed on the homepage.","info")
        return redirect(url_for('site.home'))
        

webapp/api/__init__.py
from flask import Blueprint

api=Blueprint('api',__name__)

import views

webapp/data/__init__.py
from flask import Blueprint

data=Blueprint('data',__name__)

import views

webapp/install/__init__.py
from flask import Blueprint

install = Blueprint('install', __name__, template_folder='templates', static_folder='static')

import views

webapp/modeller/__init__.py
from flask import Blueprint

modeller=Blueprint('modeller',__name__,template_folder='templates',static_folder='static')

import views

webapp/modeller/views.py
import os
import re
import subprocess
import uuid
import json

from . import modeller

from flask import g, current_app, render_template, request, jsonify, make_response, render_template, abort, redirect, url_for
from datetime import datetime, timedelta

from ..models import *

@modeller.route('/<model_name>')
def show_modeller(model_name):
    m = Model.query.filter(Model.name==model_name).first_or_404()
    if not m.validated:
        flash("Model '%s' has not been validated and cannot be run in the modeller."%(m.name),"error")
        return redirect(url_for('site.home'))
    if m.disabled:
        flash("Model has been deleted.")
        return redirect(url_for('site.home'))
        
    return render_template('modeller/modeller.html', model=m, discretization=m.discretization, u=current_user)

webapp/site/__init__.py
from flask import Blueprint

site = Blueprint('site', __name__, template_folder='templates', static_folder='static')

import views

webapp/site/views.py
import os
import re
import subprocess
import uuid
import json

from . import site

from flask import g, current_app, render_template, request, jsonify, make_response, redirect, url_for
from flask.ext.user import login_required, roles_required
from datetime import datetime, timedelta

from ..models import *


@site.route('/')
def home():
    if current_user.is_anonymous():
        return redirect(url_for('user.login'))
    else:
        #The highlighted models which are available to all users
        jobs = Job.query.order_by(Job.date_created.desc()).filter(Job.user==current_user, Job.status_code==1).limit(5)
        models = Model.query.order_by(Model.name).filter(Model.highlighted==True, Model.disabled==False).all()
        
        #The other (test) models which are not on the homepage.
        other_models = Model.query.order_by(Model.disabled, Model.name).filter(Model.highlighted==False).all()
        return render_template("site/home.html", models=models, other_models=other_models, jobs=jobs)
        
@site.route('/myaccount')
@login_required
def myaccount():
    return render_template("site/myaccount.html")
    
@site.route('/myaccount/reset-api-token')
@login_required
def myaccount_reset_api_token():
    current_user.reset_api_token()
    return redirect(url_for('site.home'))
    

@site.route('/models')
def models():
    return render_template("site/models.html", models=Model.query.all())
 
@site.route('/features')
def features():
    return render_template("site/features.html")
 
@site.route('/about')
def about():
    return render_template("site/about.html")
 
@site.route('/datasources')
def datasources():
    return render_template("site/datasources.html")
    
@site.route('/manual')
def manual():
    return render_template("site/manual.html")

webapp/status/__init__.py
from flask import Blueprint

status = Blueprint('status', __name__, template_folder='templates', static_folder='static')

import views

webapp/status/views.py
import os
import re
import subprocess
import uuid
import json

from . import status

from flask import g, current_app, render_template, request, jsonify, make_response, flash
from datetime import datetime, timedelta

from ..models import *

@status.route('')
def home():
    """
    
    Todo:
    
    - status of beanstalk queue rather than entire server
    - mappsever status
    - databsae status
    - mapserver connect
    
    """
    return render_template("status/status.html", beanstalk=beanstalk)

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
	<head>
		<title>GEMS: Global Environmental Modelling System</title>
		<link href="/static/lib/bootstrap/bootstrap.min.css" rel="stylesheet">
		<link href="/static/lib/fontawesome/css/font-awesome.min.css" rel="stylesheet">
		<link href="/static/lib/gem/gems.css" rel="stylesheet">
		{% block headcss %}{% endblock %}
		{% block headjs %}{% endblock %}
	</head>
	<body>
		{% include "warning_debug.html" %}
		{% include "warning_system.html" %}

		{% block header %}
				{% include "header.html" %}
		{% endblock %}

		{% include "flashes.html" %}

		{% block editor %}
		{% endblock %}

		{% block modeller %}
		{% endblock %}

		<div class="container-fluid">
			{% block content %}{% endblock %}
		</div>

		{% block footer %}
			{% include "footer.html" %}
		{% endblock %}
		<script src="/static/lib/jquery/jquery-1.11.2.min.js"></script>
		<script src="/static/lib/bootstrap/bootstrap.min.js"></script>
		{% block footjs %}

		{% endblock %}
	</body>
</html>

webapp/templates/debugbar.html
{% if config["DEBUG"] %}
  <style>
  div#debug-bar {
    background-color:red; 
    color:white;
    font-size:9pt;
    text-align:center;
    padding:3px;
  }
  </style>
  <div id="debug-bar">
    <strong>Debug mode is on!</strong> This can make things slow. Set DEBUG=False in local_settings.py to turn it off.
    {% if current_user.is_authenticated() %} 
      You are logged in as {{current_user.username}}. 
    {% else %}
      You are not logged in.
      {% endif %}
  </div>
{% endif %}

webapp/templates/flashes.html
<!--flashes.html-->
{% with messages = get_flashed_messages(with_categories=true,category_filter=['error','info','ok','debug']) %}
  {% if messages %}
	<div class="container-fluid" style="padding-top:17px;background-color:#fff;border-bottom:0px solid #ddd;">
		<ul class="list-group">
		{% for category,message in messages %}
			<li class="list-group-item {% if category=="debug" %}debug-item{% endif %}">
				{% if category == "error" %}
					<span style="color:red"><i class="fa fa-times-circle"></i> {{message|safe}}</span>
				{% elif category == "info" %}
					<span style="color:darkblue"><i class="fa fa-info-circle"></i></span> {{message|safe}}
				{% elif category == "ok" %}
					<span style="color:green"><i class="fa fa-check-circle"></i></span> {{message|safe}}
				{% elif category == "debug" %}
					<span style="color:orange"><i class="fa fa-minus-circle"></i></span> {{message|safe}}
				{% else %}
					<!-- ignore messages without a category -->
					<!--<span style="color:black"><i class="fa fa-dot-circle-o"></i></span> {{message|safe}}-->
				{% endif %}
			</li>
		{% endfor %}
    	</ul>
    </div>
  {% endif %}
{% endwith %}
<!--/flashes.html-->

webapp/templates/header.html
<nav class="navbar navbar-default navbar-inverse " role="navigation">
  <div class="container-fluid">
      <ul class="nav navbar-nav navbar-left" id="navbar-main">
        {% if request.path != '/' and request.path != '/user/login' %}
          <li><a href="/"><i class="fa fa-arrow-left"></i> Home</a></li>
		 {% else %}
		  <li><a href="{{url_for('site.about')}}" style="padding:0;padding-left:15px;padding-top:10px;padding-bottom:10px;padding-right:15px;"><img src="/static/gfx/gems-logo-cube.png" style="border:0;height:30px;"></a></li>
        {% endif %}
      </ul>
      <!--
      {% if not current_user.is_anonymous() %}
        <p class="navbar-text navbar-left" style="color:#ddd;">
          Logged in as <strong>{{current_user.username}}</strong>
        </p>
      {% endif %}
      -->

    {% if not current_user.is_anonymous() %}
      <a href="{{url_for('user.logout')}}" class="btn btn-default navbar-btn pull-right" style="background-color:#222;border-color:#555;color:#aaa;margin-left:15px;"><i class="fa fa-close"></i> Log Out</a>
      <a href="{{url_for('site.myaccount')}}" class="btn btn-default navbar-btn pull-right" style="background-color:#222;border-color:#555;color:#aaa;margin-left:15px;"><i class="fa fa-user"></i> My Account</a>
	  <a href="{{url_for('site.manual')}}" class="btn btn-default navbar-btn pull-right" style="background-color:#222;border-color:#555;color:#aaa;margin-left:15px;"><i class="fa fa-book"></i></a>
    {% endif %}
    <ul class="nav navbar-nav navbar-right">
      <li><a href="{{url_for('site.datasources')}}" style="color:#888;"><i class="fa fa-chevron-right"></i> Data sources and attribution</a></li>
      <li><a href="{{url_for('site.about')}}" style="color:#888;"><i class="fa fa-chevron-right"></i> About this project</a></li>
      <li><a href="{{url_for('status.home')}}" style="color:#888;"><i class="fa fa-chevron-right"></i> System status</a></li>
    </ul>

  </div>
</nav>

webapp/templates/warning_debug.html
{% if config["DEBUG"] %}
  <div class="warning-bar">
    <strong>Debug mode is on!</strong> This can make things slow. Set DEBUG=False in local_settings.py to turn it off.
    {% if current_user.is_authenticated() %} 
      You are logged in as {{current_user.username}}. 
    {% else %}
      You are not logged in.
    {% endif %}
    There are {{system_status.beanstalk_workers}} connected workers.
  </div>
{% endif %}

webapp/templates/warning_system.html
{% if system_status.beanstalk_workers > 0 %}
  
{% else %}
  <div class="warning-bar">
    <strong>Processing warning!</strong> 
    It seems like there are no GEMS workers connected to the work queue. Please start some workers. Without any workers models cannot be processed.
  </div>
{% endif %}